version: '3.8'

services:
  app:
    build: .
    container_name: flask_image_trap_app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./app/GeoLite2-City.mmdb:/app/app/GeoLite2-City.mmdb
      - .env:/app/.env
    expose:
      - "5001"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: flask_image_trap_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge